using './main.bicep'

param location = 'japaneast'
param virtualNetworkName = 'mansion-k8s-vnet'
param virtualNetworkAddressPrefix = '10.10.0.0/16'
param k8sSubnetName = 'k8s-subnet'
param k8sSubnetPrefix = '10.10.10.0/24'
param kubevirtSubnetName = 'kubevirt-subnet'
param kubevirtSubnetPrefix = '10.10.100.0/24'
param networkSecurityGroupName = 'k8s-nsg'
// Documentation placeholder; replace before deployment.
param allowedSourceCidr = '203.0.113.10/32'
param adminUsername = 'ubuntu'
param masterVmName = 'mansion-k8s-master'
param infraVmName = 'mansion-k8s-infra'
param workerVmName = 'mansion-k8s-worker'
param masterVmSize = 'Standard_D2s_v5'
param infraVmSize = 'Standard_D4s_v5'
param workerVmSize = 'Standard_D4s_v5'
param masterPrivateIp = '10.10.10.10'
param infraPrivateIp = '10.10.10.11'
param workerPrivateIp = '10.10.10.12'
param workerSecondaryPrivateIp = '10.10.100.12'
