using './main.bicep'

// Deploy to resource group: mansion_kubevirt_resource
param location = 'japaneast'
// Reference the shared VNet in mansion-shared-resource
param sharedVnetName = 'mansion-shared-vnet'
param sharedVnetResourceGroup = 'mansion-shared-resource'
// K8s node subnet — now using existing shared-node-subnet
param k8sSubnetName = 'shared-node-subnet'
// Secondary subnet for VM overlay traffic (Worker eth1 / KubeVirt VMs).
param kubevirtSubnetName = 'mansion_kubevirt_vm_subnet'
param kubevirtSubnetPrefix = '10.10.100.0/24'
param networkSecurityGroupName = 'mansion_kubevirt_nsg'
param allowedSourceCidr = '61.216.143.3/32'
param masterVmName = 'mansion_kubevirt_master'
param infraVmName = 'mansion_kubevirt_infra'
param workerVmName = 'mansion_kubevirt_worker'
param masterPublicIpName = 'mansion_kubevirt_master_pip'
param infraPublicIpName = 'mansion_kubevirt_infra_pip'
param workerPublicIpName = 'mansion_kubevirt_worker_pip'
param masterNicName = 'mansion_kubevirt_master_nic'
param infraNicName = 'mansion_kubevirt_infra_nic'
param workerNicName = 'mansion_kubevirt_worker_nic'
param workerSecondaryNicName = 'mansion_kubevirt_worker_nic2'
param masterPrivateIp = '10.10.10.24'
param infraPrivateIp = '10.10.10.25'
param workerPrivateIp = '10.10.10.26'
param workerSecondaryPrivateIp = '10.10.100.13'
param adminUsername = 'ubuntu'
param adminPublicKey = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGPrTSUgVBJAg7NEFNg17pfs2eRGd0H+xRDSU5cG4Oyp mansionlai@MansiondeMac-mini.local'
param masterVmSize = 'Standard_D2s_v4'
param infraVmSize = 'Standard_D4s_v4'
param workerVmSize = 'Standard_D4s_v4'
param imagePublisher = 'Canonical'
param imageOffer = '0001-com-ubuntu-server-jammy'
param imageSku = '22_04-lts-gen2'
param imageVersion = 'latest'
