ansible_user: ubuntu

ceph_public_network_cidr: 10.10.10.0/24
ceph_cluster_network_cidr: 172.10.10.0/24

ceph_dashboard_user: admin
ceph_dashboard_password: "{{ vault_ceph_dashboard_password }}"
ceph_version: 19.2.2
ceph_container_runtime: docker
ceph_cephadm_url: https://download.ceph.com/rpm-19.2.2/el9/noarch/cephadm
ceph_container_image: quay.io/ceph/ceph:v19.2.2

ceph_phase1_packages:
  - curl
  - wget
  - net-tools
  - vim
  - htop
  - lsof
  - chrony
  - netcat-openbsd

ceph_phase2_packages:
  - docker.io
  - lvm2
  - python3
  - python3-pip

ceph_sysctl_settings:
  kernel.pid_max: "4194303"
  fs.file-max: "26234859"
  vm.zone_reclaim_mode: "0"
  vm.swappiness: "0"
  vm.min_free_kbytes: "4194304"

ceph_rbd_pool_name: k8s_rbd_pool
ceph_rbd_pool_pg_num: 128
ceph_rbd_pool_pgp_num: 128
ceph_rbd_pool_size: 3
ceph_rbd_pool_min_size: 1
ceph_rbd_crush_rule_name: k8s_rbd_pool_rack
ceph_test_image_name: test-image
ceph_test_image_size: 10G

ceph_exporter_port: 9128
ceph_exporter_image: quay.io/digitalocean/ceph_exporter:latest

prometheus_agent_image: prom/prometheus:v2.53.0
prometheus_agent_remote_write_url: "{{ vault_prometheus_agent_remote_write_url }}"
prometheus_agent_remote_write_username: "{{ vault_prometheus_agent_remote_write_username }}"
prometheus_agent_remote_write_password: "{{ vault_prometheus_agent_remote_write_password }}"

fluent_bit_service: fluent-bit
fluent_bit_image: cr.fluentbit.io/fluent/fluent-bit:3.0.7
fluent_bit_opensearch_host: "{{ vault_fluent_bit_opensearch_host }}"
fluent_bit_opensearch_port: 9200
fluent_bit_opensearch_username: "{{ vault_fluent_bit_opensearch_username }}"
fluent_bit_opensearch_password: "{{ vault_fluent_bit_opensearch_password }}"
fluent_bit_opensearch_index: ceph-lab
