using './main.bicep'

param location = 'japaneast'
param virtualNetworkName = 'mansion_ceph_vnet'
param virtualNetworkAddressPrefix = '10.10.0.0/16'
param publicSubnetName = 'mansion_ceph_public_subnet'
param publicSubnetPrefix = '10.10.10.0/24'
param clusterSubnetName = 'mansion_ceph_cluster_subnet'
param clusterSubnetPrefix = '172.10.10.0/24'
param networkSecurityGroupName = 'mansion_ceph_nsg'
param allowedSourceCidr = '203.0.113.10/32'
param cephNode01VmName = 'ceph-node-01'
param cephNode02VmName = 'ceph-node-02'
param cephNode03VmName = 'ceph-node-03'
param cephNode01VmSize = 'Standard_D4s_v4'
param cephNode02VmSize = 'Standard_D4s_v4'
param cephNode03VmSize = 'Standard_D4s_v4'
param adminUsername = 'ubuntu'
// REQUIRED: Operators MUST replace this empty string with a valid SSH public key before deployment.
// Password authentication is disabled; SSH key authentication is mandatory.
param adminPublicKey = ''
param imagePublisher = 'Canonical'
param imageOffer = '0001-com-ubuntu-server-jammy'
param imageSku = '22_04-lts-gen2'
param imageVersion = 'latest'
param cephNode01PublicIp = '10.10.10.10'
param cephNode02PublicIp = '10.10.10.11'
param cephNode03PublicIp = '10.10.10.12'
param cephNode01ClusterIp = '172.10.10.10'
param cephNode02ClusterIp = '172.10.10.11'
param cephNode03ClusterIp = '172.10.10.12'
param dataDiskSku = 'StandardSSD_LRS'
param dataDiskSizeGb = 64
